#!/bin/bash

# Load CMSSW + Combine
export SCRAM_ARCH=el9_amd64_gcc12
cd /eos/home-l/lingqian/cmseft/statistics/CMSSW_14_1_0_pre4/src
eval `scramv1 runtime -sh`
cd -

###########################################
# SCANS (mode = data)
###########################################

# 1D scans

combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs ctGRe --freezeParameters cSM,ctGIm,cQj18,cQj38,cQj11,cQj31,ctu8,ctd8,ctj8,cQu8,cQd8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges ctGRe=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.ctGRe
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs ctGIm --freezeParameters cSM,ctGRe,cQj18,cQj38,cQj11,cQj31,ctu8,ctd8,ctj8,cQu8,cQd8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges ctGIm=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.ctGIm
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs cQj18 --freezeParameters cSM,ctGRe,ctGIm,cQj38,cQj11,cQj31,ctu8,ctd8,ctj8,cQu8,cQd8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges cQj18=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.cQj18
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs cQj38 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj11,cQj31,ctu8,ctd8,ctj8,cQu8,cQd8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges cQj38=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.cQj38
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs cQj11 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj31,ctu8,ctd8,ctj8,cQu8,cQd8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges cQj11=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.cQj11
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs cQj31 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,ctu8,ctd8,ctj8,cQu8,cQd8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges cQj31=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.cQj31
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs ctu8 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,cQj31,ctd8,ctj8,cQu8,cQd8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges ctu8=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.ctu8
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs ctd8 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,cQj31,ctu8,ctj8,cQu8,cQd8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges ctd8=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.ctd8
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs ctj8 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,cQj31,ctu8,ctd8,cQu8,cQd8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges ctj8=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.ctj8
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs cQu8 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,cQj31,ctu8,ctd8,ctj8,cQd8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges cQu8=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.cQu8
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs cQd8 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,cQj31,ctu8,ctd8,ctj8,cQu8,ctu1,ctd1,ctj1,cQu1,cQd1 --setParameterRanges cQd8=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.cQd8
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs ctu1 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,cQj31,ctu8,ctd8,ctj8,cQu8,cQd8,ctd1,ctj1,cQu1,cQd1 --setParameterRanges ctu1=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.ctu1
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs ctd1 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,cQj31,ctu8,ctd8,ctj8,cQu8,cQd8,ctu1,ctj1,cQu1,cQd1 --setParameterRanges ctd1=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.ctd1
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs ctj1 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,cQj31,ctu8,ctd8,ctj8,cQu8,cQd8,ctu1,ctd1,cQu1,cQd1 --setParameterRanges ctj1=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.ctj1
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs cQu1 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,cQj31,ctu8,ctd8,ctj8,cQu8,cQd8,ctu1,ctd1,ctj1,cQd1 --setParameterRanges cQu1=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.cQu1
combineTool.py workspace_data.root -M MultiDimFit --algo grid --points 10000 --redefineSignalPOIs cQd1 --freezeParameters cSM,ctGRe,ctGIm,cQj18,cQj38,cQj11,cQj31,ctu8,ctd8,ctj8,cQu8,cQd8,ctu1,ctd1,ctj1,cQu1 --setParameterRanges cQd1=-20.0,20.0 --X-rtd MINIMIZER_no_analytic --cminDefaultMinimizerStrategy 1 --cminFallbackAlgo Minuit2,0:0.1 --robustFit 1  -n Scan1D_data.cQd1
